In [8]:
#Importing Modules

import numpy as np
import pandas as pd

In [9]:
#Understanding the Dataset

file = pd.read_csv('online_shoppers_intention.csv')
print(file.dtypes)
file.head()

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [10]:
print('Month : ', file['Month'].unique())
print('VisitorType : ', file['VisitorType'].unique())
print('Weekend : ', file['Weekend'].unique())
print('Revenue : ', file['Revenue'].unique())

Month :  ['Feb' 'Mar' 'May' 'Oct' 'June' 'Jul' 'Aug' 'Nov' 'Sep' 'Dec']
VisitorType :  ['Returning_Visitor' 'New_Visitor' 'Other']
Weekend :  [False  True]
Revenue :  [False  True]

In [11]:
#Data Encoding

from sklearn import preprocessing

data_encoder = preprocessing.LabelEncoder()
file['Month'] = data_encoder.fit_transform(file['Month'])
file['VisitorType'] = data_encoder.fit_transform(file['VisitorType'])
file['Weekend'] = data_encoder.fit_transform(file['Weekend'])
file['Revenue'] = data_encoder.fit_transform(file['Revenue'])

#Testing Encoding
print(file.dtypes)
file.head()

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                        int32
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                  int32
Weekend                      int32
Revenue                      int32
dtype: object

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,1,1,1,1,2,0,0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,2,1,2,2,0,0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,4,1,9,3,2,0,0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,2,3,2,2,4,2,0,0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,2,3,3,1,4,2,1,0

In [12]:
X = file[['Administrative','Administrative_Duration', 'Informational', 'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration', 'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType', 'Weekend']]
print(X.shape)
Y = file[['Revenue']]
print(Y.shape)
X.head()

(12330, 17)
(12330, 1)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,1,1,1,1,2,0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,2,1,2,2,0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2,4,1,9,3,2,0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,2,3,2,2,4,2,0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,2,3,3,1,4,2,1

In [13]:
#Train/Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=15)

In [14]:
#Machine Lerning

#Support Vector Machine(SVM)
from sklearn import svm
from sklearn.metrics import accuracy_score

clf = svm.SVC(gamma='scale')
clf.fit(X_train, Y_train.values.ravel())

pred = clf.predict(X_test)
print('Accuracy using Support Vector Machine(SVM): ', 100 * accuracy_score(Y_test.values.ravel(), pred))

Accuracy using Support Vector Machine(SVM):  84.21194917545283

In [15]:
#Multilayer Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

clf = MLPClassifier(activation='logistic', solver='adam', alpha=1e-5, hidden_layer_sizes=(7, 5), learning_rate='adaptive', random_state=1)
clf.fit(X_train, Y_train.values.ravel())

pred = clf.predict(X_test)
print('Accuracy using Multilayer Perceptron: ', 100 * accuracy_score(Y_test.values.ravel(), pred))

Accuracy using Multilayer Perceptron:  89.13219789132198

In [17]:
#Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

clf = GaussianNB()
clf.fit(X_train, Y_train.values.ravel())

pred = clf.predict(X_test)
print('Accuracy using Gaussian Naive Bayes: ', 100 * accuracy_score(Y_test.values.ravel(), pred))

Accuracy using Gaussian Naive Bayes:  84.75263584752636

In [23]:
#K-Neighbors Classifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

clf = KNeighborsClassifier(n_neighbors=10)
clf.fit(X_train, Y_train.values.ravel())

pred = clf.predict(X_test)
print('Accuracy using K-Neighbors Classifier: ', 100 * accuracy_score(Y_test.values.ravel(), pred))

Accuracy using K-Neighbors Classifier:  86.18545552852123

In [28]:
#Decision Trees
from sklearn import tree
from sklearn.metrics import accuracy_score

clf = tree.DecisionTreeClassifier()
clf.fit(X_train, Y_train.values.ravel())

pred = clf.predict(X_test)
print('Accuracy using Decision Trees: ', 100 * accuracy_score(Y_test.values.ravel(), pred))

Accuracy using Decision Trees:  85.67180319005136

In [30]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
clf.fit(X_train, Y_train.values.ravel())

pred = clf.predict(X_test)
print('Accuracy using Random Forest Classifier: ', 100 * accuracy_score(Y_test.values.ravel(), pred))

Accuracy using Random Forest Classifier:  84.07677750743444

In [39]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

clf = LogisticRegression(random_state=0, solver='lbfgs',max_iter=10000, multi_class='multinomial')
clf.fit(X_train, Y_train.values.ravel())

pred = clf.predict(X_test)
print('Accuracy using LogisticRegression: ', 100 * accuracy_score(Y_test.values.ravel(), pred))

Accuracy using LogisticRegression:  87.99675587996757